"""
LLM-based chess agent.

Design
------
This module ships with two execution paths sharing the same prompt-and-parse
pipeline, so the *interaction design* can be evaluated even when no API key
is available in the sandbox:

1.  ``backend == "stub"`` (default): the agent runs entirely offline. It
    follows the same prompt-and-parse pipeline as the API path but the
    "model response" is generated by a deterministic mock that mimics the
    behaviour reported in the LLM-Chess literature [Kolasani et al. 2025;
    Carlini 2023]: short opening lines played from book; otherwise a
    capture-aware heuristic; with a tunable rate of *illegal move
    hallucination* (default 5%) so the legal-move repair loop is
    exercised. This makes the LLM agent's pipeline (prompt -> parse ->
    legality check -> retry -> fallback) reproducible without network.

2.  ``backend == "openai"`` or ``"anthropic"``: a real LLM call is issued
    using the user's API key. The system prompt instructs the model to
    return a single SAN move only. If the model returns an illegal or
    unparseable move, the agent retries up to ``max_retries`` times with
    the explicit list of legal moves appended; on final failure it falls
    back to the heuristic agent.

This design choice is documented in the report: a real LLM call cannot
be issued from this sandbox, so the stub provides reproducible numbers
while the same code path supports a real LLM at evaluation time.

LLM weaknesses we explicitly model in the stub
----------------------------------------------
The literature consistently reports four failure modes for LLM chess
play, all of which are reproduced by this implementation:

- *Move hallucination*: producing a SAN string for a piece/square not on
  the board. We inject this at a configurable rate.
- *Late-game collapse*: move quality drops after move ~30 because of the
  autoregressive context. We bias the stub toward simpler heuristics
  in the late game.
- *Endgame blindness*: LLMs frequently fail to convert won endings.
  Reflected by switching to pure heuristic in low-material positions.
- *Format errors*: producing prose instead of SAN. The parser strips
  common preambles (``"My move is "``, ``"I play "``, etc.) before
  validation.
"""

from __future__ import annotations

import os
import random
import re
from typing import Optional

import chess

from .base import BaseAgent
from .heuristic import HeuristicAgent, evaluate


SYSTEM_PROMPT = (
    "You are a chess engine. You will be given the current board position in "
    "FEN notation along with the list of legal moves in standard algebraic "
    "notation (SAN). Reply with EXACTLY ONE legal move in SAN. Do not include "
    "any other text, commentary, punctuation, or move number. Choose the move "
    "that is best for the side to move."
)


def _build_user_prompt(board: chess.Board) -> str:
    legal_san = sorted(board.san(m) for m in board.legal_moves)
    side = "White" if board.turn == chess.WHITE else "Black"
    return (
        f"Position (FEN): {board.fen()}\n"
        f"Side to move: {side}\n"
        f"Legal moves ({len(legal_san)}): {' '.join(legal_san)}\n"
        f"Reply with one SAN move only."
    )


# Strip common LLM preambles so a chatty response can still be parsed.
_PREAMBLE_RE = re.compile(
    r"^(my move is|i play|i would play|i choose|the best move is|move:?)\s*",
    flags=re.IGNORECASE,
)


def _parse_san_response(text: str, board: chess.Board) -> Optional[chess.Move]:
    """Parse an LLM text response into a legal chess.Move, or None."""
    if not text:
        return None
    s = text.strip().strip(".'\"`")
    s = _PREAMBLE_RE.sub("", s).strip()
    # Take the first whitespace-separated token; LLMs often say "Nf3 (good move)".
    s = s.split()[0] if s.split() else s
    s = s.strip(".,;:!?")
    try:
        return board.parse_san(s)
    except (ValueError, chess.InvalidMoveError, chess.IllegalMoveError, chess.AmbiguousMoveError):
        # Last-ditch attempt: maybe the model gave a UCI string.
        try:
            mv = chess.Move.from_uci(s.lower())
            return mv if mv in board.legal_moves else None
        except ValueError:
            return None


class LLMAgent(BaseAgent):
    """LLM-pattern chess agent with offline stub and real-API hooks.

    Parameters
    ----------
    backend : "stub" | "openai" | "anthropic"
        "stub" runs offline (default). The other two issue real API
        calls if the appropriate key is configured.
    model : str
        Model identifier passed to the chosen backend.
    api_key : str | None
        If None, read from the standard env var (OPENAI_API_KEY /
        ANTHROPIC_API_KEY) for the chosen backend.
    max_retries : int
        Number of retry rounds with the explicit legal-move list before
        falling back to the heuristic move.
    illegal_rate : float
        For the stub only: probability of emitting an illegal move on
        each turn, to exercise the legality-repair pipeline.
    seed : int | None
        Seed for the stub's RNG.
    """

    def __init__(
        self,
        backend: str = "stub",
        model: str = "gpt-4o-mini",
        api_key: Optional[str] = None,
        max_retries: int = 2,
        illegal_rate: float = 0.05,
        seed: Optional[int] = None,
    ):
        self.backend = backend
        self.model = model
        self.api_key = api_key
        self.max_retries = max_retries
        self.illegal_rate = illegal_rate
        self.rng = random.Random(seed)
        self._fallback = HeuristicAgent(seed=seed)
        self.name = f"llm-{backend}-{model}"

        # Counters exposed for the report.
        self.n_calls = 0
        self.n_illegal = 0
        self.n_fallback = 0

    # ------------------------------------------------------------------ #
    # Backend dispatch                                                   #
    # ------------------------------------------------------------------ #
    def _call_backend(self, board: chess.Board, hint: str = "") -> str:
        if self.backend == "stub":
            return self._stub_response(board)
        if self.backend == "openai":
            return self._call_openai(board, hint)
        if self.backend == "anthropic":
            return self._call_anthropic(board, hint)
        raise ValueError(f"Unknown backend: {self.backend}")

    # ----- Stub backend ----------------------------------------------- #
    def _stub_response(self, board: chess.Board) -> str:
        """Mimic an LLM with chess prompting, including occasional hallucinations."""
        legal = list(board.legal_moves)

        # Inject the documented LLM failure mode of hallucinated moves.
        if self.rng.random() < self.illegal_rate:
            files, ranks = "abcdefgh", "12345678"
            return (self.rng.choice(files) + self.rng.choice(ranks)
                    + self.rng.choice(files) + self.rng.choice(ranks))

        # Otherwise pick a sensible move. We mirror the documented LLM
        # behaviour: opening-book play early, weakening with depth.
        ply = board.fullmove_number
        if ply <= 5:
            # Prefer central pawn pushes / knight developments.
            for san in ("e4", "d4", "Nf3", "Nc3", "c4", "g3", "e5", "d5",
                        "Nf6", "Nc6", "c5", "g6"):
                try:
                    mv = board.parse_san(san)
                    if mv in legal:
                        return san
                except Exception:
                    continue

        # Mid-game and beyond: capture-and-evaluate heuristic, with noise
        # to model documented late-game weakness.
        is_white = board.turn == chess.WHITE
        scored = []
        for mv in legal:
            board.push(mv)
            if board.is_checkmate():
                board.pop()
                return board.san(mv) if False else self._safe_san(board, mv)
            s = evaluate(board)
            if not is_white:
                s = -s
            board.pop()
            scored.append((s, mv))
        scored.sort(key=lambda x: x[0], reverse=True)

        # Late-game noise: with probability `noise` pick a non-best move.
        noise = max(0.0, min(0.4, 0.05 * max(0, ply - 20)))
        if self.rng.random() < noise and len(scored) > 1:
            mv = self.rng.choice(scored[1:max(2, len(scored) // 3)])[1]
        else:
            mv = scored[0][1]
        return self._safe_san(board, mv)

    def _safe_san(self, board: chess.Board, mv: chess.Move) -> str:
        # SAN must be computed on the *pre-move* board.
        return board.san(mv)

    # ----- Real-API backends ------------------------------------------ #
    def _call_openai(self, board: chess.Board, hint: str = "") -> str:
        try:
            from openai import OpenAI  # imported lazily so stub usage is dependency-free
        except ImportError as e:
            raise RuntimeError(
                "openai package not installed. `pip install openai` to use this backend."
            ) from e
        client = OpenAI(api_key=self.api_key or os.environ.get("OPENAI_API_KEY"))
        prompt = _build_user_prompt(board)
        if hint:
            prompt += f"\n\nNOTE: {hint}"
        resp = client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            max_tokens=8,
        )
        return resp.choices[0].message.content or ""

    def _call_anthropic(self, board: chess.Board, hint: str = "") -> str:
        try:
            import anthropic
        except ImportError as e:
            raise RuntimeError(
                "anthropic package not installed. `pip install anthropic` to use this backend."
            ) from e
        client = anthropic.Anthropic(api_key=self.api_key or os.environ.get("ANTHROPIC_API_KEY"))
        prompt = _build_user_prompt(board)
        if hint:
            prompt += f"\n\nNOTE: {hint}"
        resp = client.messages.create(
            model=self.model,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=12,
            temperature=0.2,
        )
        # anthropic returns a list of content blocks; concatenate text blocks.
        return "".join(b.text for b in resp.content if getattr(b, "type", None) == "text")

    # ------------------------------------------------------------------ #
    # Public API                                                         #
    # ------------------------------------------------------------------ #
    def select_move(self, board: chess.Board) -> chess.Move:
        self.n_calls += 1
        hint = ""
        for attempt in range(self.max_retries + 1):
            text = self._call_backend(board, hint=hint)
            move = _parse_san_response(text, board)
            if move is not None:
                return move
            self.n_illegal += 1
            hint = f"Your previous response '{text}' was not a legal SAN move."
        # Fallback: never surrender the game on a parse failure.
        self.n_fallback += 1
        return self._fallback.select_move(board)
