# -*- coding: utf-8 -*-
"""ProperIdentityRoots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c7s-2pwROPafFRqmLTxw1KwrlFGHXN3I
"""

import math
from itertools import permutations

# =========================================================
# Permutation / matrix utilities
# =========================================================

def perm_to_matrix(perm):
    """
    Convert a permutation (tuple/list of length n with values 1..n)
    to its n x n permutation matrix (list of lists of 0/1).
    Row i has a 1 in column perm[i] - 1.
    """
    n = len(perm)
    P = [[0] * n for _ in range(n)]
    for i, image in enumerate(perm):
        P[i][image - 1] = 1
    return P


def matmul(A, B):
    """Multiply two square matrices A and B."""
    n = len(A)
    C = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            s = 0
            for k in range(n):
                s += A[i][k] * B[k][j]
            C[i][j] = s
    return C


def identity_matrix(n):
    """Return the n x n identity matrix."""
    I = [[0] * n for _ in range(n)]
    for i in range(n):
        I[i][i] = 1
    return I


def matrices_equal(A, B):
    """Check if two matrices A and B are equal entrywise."""
    return all(rowA == rowB for rowA, rowB in zip(A, B))


# =========================================================
# Proper square roots of the identity for n = 4
# =========================================================

def is_proper_square_root_perm(perm):
    """
    Given a permutation perm of {1,...,n}, check if its permutation
    matrix P is a proper square root of the identity:
      - P^2 = I_n
      - P != I_n
    """
    n = len(perm)
    P = perm_to_matrix(perm)
    P2 = matmul(P, P)
    I = identity_matrix(n)

    # Must be a square root of identity
    if not matrices_equal(P2, I):
        return False

    # Must not be the identity permutation itself
    if perm == tuple(range(1, n + 1)):
        return False

    return True


def proper_square_roots_Id4():
    """
    Return a list of permutations of {1,2,3,4} whose permutation matrices
    are proper square roots of I4.
    """
    n = 4
    props = []
    for perm in permutations(range(1, n + 1)):
        if is_proper_square_root_perm(perm):
            props.append(perm)
    return props


def print_matrix(M):
    """Nicely print a matrix M (list of lists)."""
    for row in M:
        print(" ".join(str(x) for x in row))


def list_all_proper_square_roots_Id4():
    """Print all proper square roots of Id4 as permutations and matrices."""
    props = proper_square_roots_Id4()
    print("\nAll proper square roots of the identity matrix Id4:\n")
    for idx, perm in enumerate(props, start=1):
        print(f"{idx}. Permutation: {perm}")
        P = perm_to_matrix(perm)
        print_matrix(P)
        print()  # blank line between matrices


# =========================================================
# Counting #PSQRID(n) using involution formula
# =========================================================

def involution_count(n):
    """
    Count all permutations of {1,...,n} that are involutions,
    i.e. composed only of fixed points and 2-cycles.
    Formula:
        I(n) = sum_{k=0}^{floor(n/2)} C(n, 2k) * (2k)! / (2^k k!)
    """
    total = 0
    for k in range(0, n // 2 + 1):
        choose_2k = math.comb(n, 2 * k)
        pairings = math.factorial(2 * k) // (2 ** k * math.factorial(k))
        total += choose_2k * pairings
    return total


def psqrid(n):
    """
    Number of proper square roots of the identity matrix Id_n.
    This is equal to the number of involutions minus 1 (remove identity).
    """
    return involution_count(n) - 1


# =========================================================
# User interface: Option A and Option B
# =========================================================

def option_print_all():
    """
    Option A:
    Print #PSQRID(n) for n = 1..20,
    then list all proper square roots of Id4.
    """
    print("\nValues of #PSQRID(n) for n = 1..20:\n")
    for n in range(1, 21):
        value = psqrid(n)
        print(f"#PSQRID({n}) = {value}")
    # After printing all, also list proper square roots of Id4
    list_all_proper_square_roots_Id4()


def option_single_n():
    """
    Option B:
    Ask user for a single n (1..20), print #PSQRID(n),
    then list all proper square roots of Id4.
    """
    try:
        n = int(input("\nEnter an integer n between 1 and 20: ").strip())
    except ValueError:
        print("Invalid input. Please enter an integer.")
        return

    if not (1 <= n <= 20):
        print("n must be between 1 and 20.")
        return

    value = psqrid(n)
    print(f"\nNumber of proper square roots of Id{n}: #PSQRID({n}) = {value}")
    # After this, also list proper square roots of Id4
    list_all_proper_square_roots_Id4()


def main():
    print("====================================================")
    print(" ProperIdentityRoots.py")
    print(" This program works with proper square roots B of the")
    print(" identity matrix Id_n, where B is a permutation matrix")
    print(" such that B^2 = Id_n and B != Id_n.")
    print(" It can:")
    print("   1) Print #PSQRID(n) for all n from 1 to 20,")
    print("      and list all proper square roots of Id4; or")
    print("   2) Compute #PSQRID(n) for a single chosen n (1..20)")
    print("      and then list all proper square roots of Id4.")
    print("====================================================\n")

    print("Choose an option:")
    print("  1 - Print all #PSQRID(1)..#PSQRID(20) and Id4 roots")
    print("  2 - Enter a single n (1..20) and see #PSQRID(n)")
    choice = input("\nYour choice (1 or 2): ").strip()

    if choice == "1":
        option_print_all()
    elif choice == "2":
        option_single_n()
    else:
        print("Invalid choice. Please run the program again and choose 1 or 2.")


if __name__ == "__main__":
    main()